services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stuvy-net
  
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB: ${DATABASE_DB}
    depends_on:
      - postgresql
    networks:
      - stuvy-net
  
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    environment:
      API_URL: ${API_URL:-http://backend:8080}
    depends_on:
      - backend

networks:
  stuvy-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local