services:

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 321
      POSTGRES_DB: stuvy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stuvy-net
  
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgresql:5432/stuvy
      DB_USER: root
      DB_PASSWORD: 321
    depends_on:
      - postgresql
    networks:
      - stuvy-net

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend

networks:
  stuvy-net:
    driver: bridge

volumes:
  postgres_data:
